version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        platform: linux/x86_64
        working_dir: /code
        ports:
          - "80:8000"
        networks:
            - backend
            - app

networks:
    backend:
    app:
