version: "3"

services:
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        platform: linux/x86_64
        working_dir: /code
        networks:
            - backend
            - app
        ports:
            - "8000"
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure

    nginx:
        image: nginx
        platform: linux/x86_64
        working_dir: /code
        networks:
            - backend
            - nginx
        ports:
          - "80:80"
        volumes:
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - app

networks:
    backend:
    app:
    nginx:
